#!/bin/sh

set -eu

python3 4_detect_and_respond_to_pedestrian_crossing_red.py
python3 4_detect_and_respond_to_pedestrian_crossing_red_night.py
python3 4_detect_and_respond_to_pedestrian_walking_in_street.py
python3 4_detect_and_respond_to_pedestrian_walking_in_street_rainy.py
# python3 4_detect_and_respond_to_pedestrian_crossing_red.py
# python3 4_detect_and_respond_to_pedestrian_crossing_red_night.py
# python3 4_detect_and_respond_to_pedestrian_walking_in_street.py
# python3 4_detect_and_respond_to_pedestrian_walking_in_street_rainy.py
